// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestaoConsultasUVV.Data;

#nullable disable

namespace SistemaGestaoConsultasUVV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902135142_AddMedicos")]
    partial class AddMedicos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crm = "CRM-ES 10231",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            Nome = "Helena Marques",
                            Resumo = "Cuida da saúde de adultos, trata doenças comuns e faz o direcionamento para especialistas."
                        },
                        new
                        {
                            Id = 2,
                            Crm = "CRM-ES 10488",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            Nome = "Rafael Toledo",
                            Resumo = "Atendimento clínico geral, check-up e acompanhamento de doenças crônicas."
                        },
                        new
                        {
                            Id = 3,
                            Crm = "CRM-ES 11002",
                            Especialidade = "Pediatria",
                            Nome = "Beatriz Nogueira",
                            Resumo = "Acompanhamento do crescimento, prevenção e tratamento de doenças em bebês, crianças e adolescentes."
                        },
                        new
                        {
                            Id = 4,
                            Crm = "CRM-ES 11079",
                            Especialidade = "Pediatria",
                            Nome = "Thiago Ramalho",
                            Resumo = "Puericultura, vacinação e cuidados pediátricos de rotina."
                        },
                        new
                        {
                            Id = 5,
                            Crm = "CRM-ES 12140",
                            Especialidade = "Ginecologia e Obstetrícia",
                            Nome = "Carolina Bastos",
                            Resumo = "Saúde reprodutiva e íntima da mulher, além do acompanhamento da gravidez e do parto."
                        },
                        new
                        {
                            Id = 6,
                            Crm = "CRM-ES 12233",
                            Especialidade = "Ginecologia e Obstetrícia",
                            Nome = "Priscila Andrade",
                            Resumo = "Consultas ginecológicas de rotina, planejamento familiar e pré-natal."
                        },
                        new
                        {
                            Id = 7,
                            Crm = "CRM-ES 13051",
                            Especialidade = "Cardiologia",
                            Nome = "Anderson Vieira",
                            Resumo = "Trata do coração e do sistema circulatório, como pressão alta e exames de rotina preventiva."
                        },
                        new
                        {
                            Id = 8,
                            Crm = "CRM-ES 13188",
                            Especialidade = "Cardiologia",
                            Nome = "Marina Cavalcanti",
                            Resumo = "Avaliação de risco cardiovascular, eletrocardiograma e acompanhamento de hipertensão."
                        },
                        new
                        {
                            Id = 9,
                            Crm = "CRM-ES 14075",
                            Especialidade = "Ortopedia e Traumatologia",
                            Nome = "Gustavo Peixoto",
                            Resumo = "Cuida de problemas nos ossos, músculos, articulações e dores nas costas ou nos membros."
                        },
                        new
                        {
                            Id = 10,
                            Crm = "CRM-ES 14202",
                            Especialidade = "Ortopedia e Traumatologia",
                            Nome = "Leonardo Faria",
                            Resumo = "Lesões esportivas, fraturas e reabilitação do sistema locomotor."
                        },
                        new
                        {
                            Id = 11,
                            Crm = "CRM-ES 15019",
                            Especialidade = "Dermatologia",
                            Nome = "Luísa Fontes",
                            Resumo = "Trata de doenças da pele, cabelos e unhas."
                        },
                        new
                        {
                            Id = 12,
                            Crm = "CRM-ES 15144",
                            Especialidade = "Dermatologia",
                            Nome = "Bruno Salgado",
                            Resumo = "Dermatologia clínica, acne, alergias de pele e avaliação de manchas."
                        },
                        new
                        {
                            Id = 13,
                            Crm = "CRM-ES 16033",
                            Especialidade = "Oftalmologia",
                            Nome = "Eduardo Lins",
                            Resumo = "Cuida da saúde dos olhos e da visão."
                        },
                        new
                        {
                            Id = 14,
                            Crm = "CRM-ES 16170",
                            Especialidade = "Oftalmologia",
                            Nome = "Tatiana Rocha",
                            Resumo = "Exames de vista, adaptação de óculos e acompanhamento de doenças oculares."
                        });
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Consulta", b =>
                {
                    b.HasOne("SistemaGestaoConsultasUVV.Models.Medico", "Medico")
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestaoConsultasUVV.Models.Usuario", "Usuario")
                        .WithMany("Consultas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Medico", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Usuario", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
