// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestaoConsultasUVV.Data;

#nullable disable

namespace SistemaGestaoConsultasUVV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902141837_HorariosReservadosESeed")]
    partial class HorariosReservadosESeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("MedicoId", "DataHora")
                        .IsUnique();

                    b.ToTable("Consultas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataHora = new DateTime(2027, 5, 6, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Avaliação de exames",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            MedicoId = 1,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 2,
                            DataHora = new DateTime(2026, 12, 28, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Primeira avaliação",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            MedicoId = 1,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 3,
                            DataHora = new DateTime(2026, 12, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retorno",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            MedicoId = 1,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 4,
                            DataHora = new DateTime(2027, 4, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Revisão anual",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            MedicoId = 2,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            DataHora = new DateTime(2027, 5, 17, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Encaixe",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            MedicoId = 2,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 6,
                            DataHora = new DateTime(2026, 11, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Consulta de rotina",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            MedicoId = 2,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 7,
                            DataHora = new DateTime(2026, 10, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Revisão anual",
                            Especialidade = "Pediatria",
                            MedicoId = 3,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 8,
                            DataHora = new DateTime(2026, 11, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Primeira avaliação",
                            Especialidade = "Pediatria",
                            MedicoId = 3,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 9,
                            DataHora = new DateTime(2027, 1, 18, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Primeira avaliação",
                            Especialidade = "Pediatria",
                            MedicoId = 3,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 10,
                            DataHora = new DateTime(2027, 1, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Primeira avaliação",
                            Especialidade = "Pediatria",
                            MedicoId = 4,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 11,
                            DataHora = new DateTime(2026, 11, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Encaixe",
                            Especialidade = "Pediatria",
                            MedicoId = 4,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 12,
                            DataHora = new DateTime(2026, 10, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Consulta preventiva",
                            Especialidade = "Pediatria",
                            MedicoId = 4,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 13,
                            DataHora = new DateTime(2027, 6, 23, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Consulta de rotina",
                            Especialidade = "Ginecologia e Obstetrícia",
                            MedicoId = 5,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 14,
                            DataHora = new DateTime(2027, 3, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retorno",
                            Especialidade = "Ginecologia e Obstetrícia",
                            MedicoId = 5,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 15,
                            DataHora = new DateTime(2026, 9, 14, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Avaliação de exames",
                            Especialidade = "Ginecologia e Obstetrícia",
                            MedicoId = 5,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 16,
                            DataHora = new DateTime(2026, 12, 14, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Acompanhamento",
                            Especialidade = "Ginecologia e Obstetrícia",
                            MedicoId = 6,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 17,
                            DataHora = new DateTime(2027, 4, 7, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Consulta de rotina",
                            Especialidade = "Ginecologia e Obstetrícia",
                            MedicoId = 6,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 18,
                            DataHora = new DateTime(2027, 1, 27, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retorno",
                            Especialidade = "Ginecologia e Obstetrícia",
                            MedicoId = 6,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 19,
                            DataHora = new DateTime(2027, 2, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retorno",
                            Especialidade = "Cardiologia",
                            MedicoId = 7,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 20,
                            DataHora = new DateTime(2027, 5, 19, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Consulta de rotina",
                            Especialidade = "Cardiologia",
                            MedicoId = 7,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 21,
                            DataHora = new DateTime(2027, 5, 26, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Acompanhamento",
                            Especialidade = "Cardiologia",
                            MedicoId = 7,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 22,
                            DataHora = new DateTime(2027, 3, 24, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Consulta preventiva",
                            Especialidade = "Cardiologia",
                            MedicoId = 8,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 23,
                            DataHora = new DateTime(2027, 2, 1, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Primeira avaliação",
                            Especialidade = "Cardiologia",
                            MedicoId = 8,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 24,
                            DataHora = new DateTime(2027, 5, 11, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retorno",
                            Especialidade = "Cardiologia",
                            MedicoId = 8,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 25,
                            DataHora = new DateTime(2027, 4, 19, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retorno",
                            Especialidade = "Ortopedia e Traumatologia",
                            MedicoId = 9,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 26,
                            DataHora = new DateTime(2027, 1, 1, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Revisão anual",
                            Especialidade = "Ortopedia e Traumatologia",
                            MedicoId = 9,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 27,
                            DataHora = new DateTime(2027, 6, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Encaixe",
                            Especialidade = "Ortopedia e Traumatologia",
                            MedicoId = 9,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 28,
                            DataHora = new DateTime(2027, 5, 14, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Avaliação de exames",
                            Especialidade = "Ortopedia e Traumatologia",
                            MedicoId = 10,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 29,
                            DataHora = new DateTime(2027, 3, 12, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Consulta de rotina",
                            Especialidade = "Ortopedia e Traumatologia",
                            MedicoId = 10,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 30,
                            DataHora = new DateTime(2026, 9, 22, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retorno",
                            Especialidade = "Ortopedia e Traumatologia",
                            MedicoId = 10,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 31,
                            DataHora = new DateTime(2027, 4, 16, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retorno",
                            Especialidade = "Dermatologia",
                            MedicoId = 11,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 32,
                            DataHora = new DateTime(2027, 3, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Primeira avaliação",
                            Especialidade = "Dermatologia",
                            MedicoId = 11,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 33,
                            DataHora = new DateTime(2026, 12, 31, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Encaixe",
                            Especialidade = "Dermatologia",
                            MedicoId = 11,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 34,
                            DataHora = new DateTime(2027, 4, 8, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Consulta de rotina",
                            Especialidade = "Dermatologia",
                            MedicoId = 12,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 35,
                            DataHora = new DateTime(2026, 12, 11, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Primeira avaliação",
                            Especialidade = "Dermatologia",
                            MedicoId = 12,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 36,
                            DataHora = new DateTime(2027, 4, 28, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Consulta preventiva",
                            Especialidade = "Dermatologia",
                            MedicoId = 12,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 37,
                            DataHora = new DateTime(2027, 3, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Avaliação de exames",
                            Especialidade = "Oftalmologia",
                            MedicoId = 13,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 38,
                            DataHora = new DateTime(2026, 12, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Acompanhamento",
                            Especialidade = "Oftalmologia",
                            MedicoId = 13,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 39,
                            DataHora = new DateTime(2027, 5, 3, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Retorno",
                            Especialidade = "Oftalmologia",
                            MedicoId = 13,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 40,
                            DataHora = new DateTime(2026, 12, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Encaixe",
                            Especialidade = "Oftalmologia",
                            MedicoId = 14,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 41,
                            DataHora = new DateTime(2027, 6, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Encaixe",
                            Especialidade = "Oftalmologia",
                            MedicoId = 14,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 42,
                            DataHora = new DateTime(2027, 5, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Acompanhamento",
                            Especialidade = "Oftalmologia",
                            MedicoId = 14,
                            UsuarioId = 3
                        });
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Crm = "CRM-ES 10231",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            Nome = "Helena Marques",
                            Resumo = "Cuida da saúde de adultos, trata doenças comuns e faz o direcionamento para especialistas."
                        },
                        new
                        {
                            Id = 2,
                            Crm = "CRM-ES 10488",
                            Especialidade = "Clínica Médica (Clínico Geral)",
                            Nome = "Rafael Toledo",
                            Resumo = "Atendimento clínico geral, check-up e acompanhamento de doenças crônicas."
                        },
                        new
                        {
                            Id = 3,
                            Crm = "CRM-ES 11002",
                            Especialidade = "Pediatria",
                            Nome = "Beatriz Nogueira",
                            Resumo = "Acompanhamento do crescimento, prevenção e tratamento de doenças em bebês, crianças e adolescentes."
                        },
                        new
                        {
                            Id = 4,
                            Crm = "CRM-ES 11079",
                            Especialidade = "Pediatria",
                            Nome = "Thiago Ramalho",
                            Resumo = "Puericultura, vacinação e cuidados pediátricos de rotina."
                        },
                        new
                        {
                            Id = 5,
                            Crm = "CRM-ES 12140",
                            Especialidade = "Ginecologia e Obstetrícia",
                            Nome = "Carolina Bastos",
                            Resumo = "Saúde reprodutiva e íntima da mulher, além do acompanhamento da gravidez e do parto."
                        },
                        new
                        {
                            Id = 6,
                            Crm = "CRM-ES 12233",
                            Especialidade = "Ginecologia e Obstetrícia",
                            Nome = "Priscila Andrade",
                            Resumo = "Consultas ginecológicas de rotina, planejamento familiar e pré-natal."
                        },
                        new
                        {
                            Id = 7,
                            Crm = "CRM-ES 13051",
                            Especialidade = "Cardiologia",
                            Nome = "Anderson Vieira",
                            Resumo = "Trata do coração e do sistema circulatório, como pressão alta e exames de rotina preventiva."
                        },
                        new
                        {
                            Id = 8,
                            Crm = "CRM-ES 13188",
                            Especialidade = "Cardiologia",
                            Nome = "Marina Cavalcanti",
                            Resumo = "Avaliação de risco cardiovascular, eletrocardiograma e acompanhamento de hipertensão."
                        },
                        new
                        {
                            Id = 9,
                            Crm = "CRM-ES 14075",
                            Especialidade = "Ortopedia e Traumatologia",
                            Nome = "Gustavo Peixoto",
                            Resumo = "Cuida de problemas nos ossos, músculos, articulações e dores nas costas ou nos membros."
                        },
                        new
                        {
                            Id = 10,
                            Crm = "CRM-ES 14202",
                            Especialidade = "Ortopedia e Traumatologia",
                            Nome = "Leonardo Faria",
                            Resumo = "Lesões esportivas, fraturas e reabilitação do sistema locomotor."
                        },
                        new
                        {
                            Id = 11,
                            Crm = "CRM-ES 15019",
                            Especialidade = "Dermatologia",
                            Nome = "Luísa Fontes",
                            Resumo = "Trata de doenças da pele, cabelos e unhas."
                        },
                        new
                        {
                            Id = 12,
                            Crm = "CRM-ES 15144",
                            Especialidade = "Dermatologia",
                            Nome = "Bruno Salgado",
                            Resumo = "Dermatologia clínica, acne, alergias de pele e avaliação de manchas."
                        },
                        new
                        {
                            Id = 13,
                            Crm = "CRM-ES 16033",
                            Especialidade = "Oftalmologia",
                            Nome = "Eduardo Lins",
                            Resumo = "Cuida da saúde dos olhos e da visão."
                        },
                        new
                        {
                            Id = 14,
                            Crm = "CRM-ES 16170",
                            Especialidade = "Oftalmologia",
                            Nome = "Tatiana Rocha",
                            Resumo = "Exames de vista, adaptação de óculos e acompanhamento de doenças oculares."
                        });
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2026, 8, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.lima@exemplo.com",
                            Nome = "Ana Beatriz Lima",
                            Senha = "AQAAAAIAAYagAAAAEEKGBmDdGTsidMiEV29WxyhM6+h2x6HnF9uE84PAUqyQNISeUzUaLmrkscoD2Nn1Pw=="
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2026, 8, 2, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carlos.souza@exemplo.com",
                            Nome = "Carlos Henrique Souza",
                            Senha = "AQAAAAIAAYagAAAAEEKGBmDdGTsidMiEV29WxyhM6+h2x6HnF9uE84PAUqyQNISeUzUaLmrkscoD2Nn1Pw=="
                        },
                        new
                        {
                            Id = 3,
                            DataCadastro = new DateTime(2026, 8, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fernanda.rocha@exemplo.com",
                            Nome = "Fernanda Rocha",
                            Senha = "AQAAAAIAAYagAAAAEEKGBmDdGTsidMiEV29WxyhM6+h2x6HnF9uE84PAUqyQNISeUzUaLmrkscoD2Nn1Pw=="
                        },
                        new
                        {
                            Id = 4,
                            DataCadastro = new DateTime(2026, 8, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao.almeida@exemplo.com",
                            Nome = "João Pedro Almeida",
                            Senha = "AQAAAAIAAYagAAAAEEKGBmDdGTsidMiEV29WxyhM6+h2x6HnF9uE84PAUqyQNISeUzUaLmrkscoD2Nn1Pw=="
                        },
                        new
                        {
                            Id = 5,
                            DataCadastro = new DateTime(2026, 8, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariana.costa@exemplo.com",
                            Nome = "Mariana Costa",
                            Senha = "AQAAAAIAAYagAAAAEEKGBmDdGTsidMiEV29WxyhM6+h2x6HnF9uE84PAUqyQNISeUzUaLmrkscoD2Nn1Pw=="
                        },
                        new
                        {
                            Id = 6,
                            DataCadastro = new DateTime(2026, 8, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paulo.nunes@exemplo.com",
                            Nome = "Paulo Ricardo Nunes",
                            Senha = "AQAAAAIAAYagAAAAEEKGBmDdGTsidMiEV29WxyhM6+h2x6HnF9uE84PAUqyQNISeUzUaLmrkscoD2Nn1Pw=="
                        },
                        new
                        {
                            Id = 7,
                            DataCadastro = new DateTime(2026, 8, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "renata.dias@exemplo.com",
                            Nome = "Renata Dias",
                            Senha = "AQAAAAIAAYagAAAAEEKGBmDdGTsidMiEV29WxyhM6+h2x6HnF9uE84PAUqyQNISeUzUaLmrkscoD2Nn1Pw=="
                        },
                        new
                        {
                            Id = 8,
                            DataCadastro = new DateTime(2026, 8, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tiago.moreira@exemplo.com",
                            Nome = "Tiago Moreira",
                            Senha = "AQAAAAIAAYagAAAAEEKGBmDdGTsidMiEV29WxyhM6+h2x6HnF9uE84PAUqyQNISeUzUaLmrkscoD2Nn1Pw=="
                        });
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Consulta", b =>
                {
                    b.HasOne("SistemaGestaoConsultasUVV.Models.Medico", "Medico")
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaGestaoConsultasUVV.Models.Usuario", "Usuario")
                        .WithMany("Consultas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Medico", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("SistemaGestaoConsultasUVV.Models.Usuario", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
